---
title: "ChooseYourOwn_Report"
author: "Will Powers"
date: "12/28/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
The report documents the analysis and presents the findings, along with supporting statistics and figures. In order to demonstrate your understanding of course material, please provide thorough explanation or justification for various steps of your project, such as why a specific train/test split (e.g. 50/50 vs 90/10) or algorithm was used.

#	Overview 

TODO: Summarize Following information about the data

```
Patients with Liver disease have been continuously increasing because of excessive consumption of alcohol, inhale of harmful gases, intake of contaminated food, pickles and drugs. This dataset was used to evaluate prediction algorithms in an effort to reduce burden on doctors.

This data set contains 416 liver patient records and 167 non liver patient records collected from North East of Andhra Pradesh, India. The "Dataset" column is a class label used to divide groups into liver patient (liver disease) or not (no disease). This data set contains 441 male patient records and 142 female patient records.

Any patient whose age exceeded 89 is listed as being of age "90".
```


## The Dataset

https://www.kaggle.com/uciml/indian-liver-patient-records

     
     https://www.kaggle.com/new-york-city/nyc-property-sales
     - modified to have sale prices into X categories 
            - based on census project https://www.kaggle.com/uciml/adult-census-income
            
      ^^^ MAYBE.... CHECK OTHER EXAMPLES And SEE what novel things you can do with Regression
      
     
## Variables

##	Project Goals

##	Key Steps

#	Methods & Analysis
## Process 
## Techniques
### Data Cleaning
###	Data Exploration 
###	Data Visualization
###	Insights 
###	Modeling Approach

 At least two different models or algorithms must be used, with at least one being more advanced than linear or logistic regression for prediction problems.

#	Final Model
##	Results 
        RMSE <= .86490
##	Performance

#	conclusion
##	Summary
##	Limitations 
##	Future work
